preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jit-pack:
  sonatype-oss-releases:
  rovo89-xposed-api:
    scope: LIBRARIES
    url: https://api.xposed.info/
    content:
      include:
        group:
          de.robv.android.xposed


plugins:
  com.android.application:
    alias: android-application
    version: 8.9.0
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 2.1.10
  org.jetbrains.kotlin.plugin.compose:
    alias: kotlin-compose
    version: 2.1.10
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 2.1.10
  com.google.devtools.ksp:
    alias: kotlin-ksp
    version: 2.1.10-1.0.31
  com.google.dagger.hilt.android:
    alias: hilt-android
    version: 2.57.1


libraries:
  androidx.core:
    core-ktx:
      version: 1.16.0
    core-splashscreen:
      version: 1.0.1
  androidx.lifecycle:
    lifecycle-runtime-ktx:
      version: 2.9.1
  androidx.activity:
    activity-compose:
      version: 1.10.1
  androidx.compose:
    compose-bom:
      version: 2024.09.00
  androidx.compose.ui:
    ui:
      version: <no-spec>
    ui-graphics:
      version: <no-spec>
    ui-tooling:
      version: <no-spec>
    ui-tooling-preview:
      version: <no-spec>
    ui-test-manifest:
      version: <no-spec>
    ui-test-junit4:
      version: <no-spec>
  androidx.compose.material3:
    material3:
      version: <no-spec>
  com.google.android.material:
    material:
      version: 1.12.0
  junit:
    junit:
      version: 4.13.2
  androidx.test.ext:
    junit:
      version: 1.2.1
  androidx.test.espresso:
    espresso-core:
      version: 3.6.1
  com.google.devtools.ksp:
    symbol-processing-api:
      version: 2.1.10-1.0.29
  com.squareup:
    kotlinpoet-ksp:
      version: 2.0.0
  androidx.appcompat:
    appcompat:
      version: 1.7.0
  androidx.navigation:
    navigation-compose:
      version: 2.8.8
  com.google.accompanist:
    accompanist-navigation-animation:
      version: 0.24.1
  androidx.compose.material:
    material-icons-extended:
      version: 1.7.8

  io.github.moriafly:
    salt-ui:
      version: 2.0.0
  com.google.code.gson:
    gson:
      version: 2.9.0
  io.github.billywei01:
    fastkv:
      version: 3.0.1
  com.google.dagger:
    hilt-android:
      version: 2.57.1
    hilt-android-compiler:
      version: 2.57.1